name: flutter_analytics_example
description: an example
version: 0.6.7+5

environment:
  flutter: '>1.7.8 <2.0.0'
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_analytics:
    path: ../

flutter:
  uses-material-design: true
